### ISSUE TITLE
Feature: Song config

### ISSUE THREAD

**Issue by iplusplus42** [Okazari/atom-play-piano#1]
The two songs that are built in are cool, but it would be really cool if there was a config where we could put songs in using the note variables.

**Comment by Okazari** [comment]
I'm looking for a way to give users the opportunity to tune in their own songs.
I have several solutions in my mind.

Option 1
======

The best one so far in my opinion is this one :
 - prompt for a string array
 - ask the song name
 - add it to the Atom play piano package top menu.
 - Persist it into the serializedState of the package.

Pros : 
 - You can add as much song as you like

Cons : 
 - A bit longer to do. Not actually sure how i could prompt for the musicsheet and name.

Option 2
======
For a faster result, i could just put some "Free slots" that could be overrided in the package settings.
Pros : 
 - Easy and fast

Cons : 
- The number of custom songs will be limited.

I'll be probably starting with the second solution, i'll try the first one if i have some free time.

Anyway, if you want to permanently add a song and share it for any users, pull request are welcome ;) !


WDYT ?

**Comment by Okazari** [comment]
As requested, in the new v3.2.0, you can now configure up to Three custom songs for atom-play-piano package.
You can refer to the updated read-me for how you can configure them.

Hope you'll like it :) !
